# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbJOovGdOMNtkawsaqyeHYLAVHTakaGS
"""

import streamlit as st

# Konfigurasi Halaman Dashboard
st.set_page_config(
    page_title="Portal Aplikasi Didik Purwanto",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Styling CSS tambahan agar tampilan kartu lebih menarik dan rapi
st.markdown(
    """
    <style>
    .main-header {
        font-size: 2.2rem;
        font-weight: 700;
        color: #1E3A8A;
        margin-bottom: 0.2rem;
    }
    .sub-header {
        font-size: 1.1rem;
        color: #4B5563;
        margin-bottom: 2rem;
    }
    .card {
        background-color: #F8FAFC;
        border: 1px solid #E2E8F0;
        padding: 20px;
        border-radius: 12px;
        margin-bottom: 20px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.02);
        transition: transform 0.2s;
    }
    .card:hover {
        transform: translateY(-3px);
        box-shadow: 0 4px 8px rgba(0,0,0,0.05);
        border-color: #3B82F6;
    }
    </style>
""",
    unsafe_allow_html=True,
)

# --- SIDEBAR NAVIGASI & FILTER ---
st.sidebar.title("🎛️ Navigasi Dashboard")
st.sidebar.markdown("Pilih kategori aplikasi yang ingin ditampilkan:")

kategori_pilihan = st.sidebar.selectbox(
    "Filter Kategori:",
    [
        "Semua Kategori",
        "⚡ Energi Terbarukan & PLTS",
        "🌊 Kelautan & Infrastruktur Air",
        "📈 Keuangan & Analisis Saham",
        "🔗 Utilitas & Referensi",
    ],
)

st.sidebar.markdown("---")
st.sidebar.info(
    "💡 **Tips:** Anda dapat membuka link di tab baru atau menggunakan fitur *Preview dalam Dashboard* di bagian bawah halaman."
)
st.sidebar.markdown("Dibuat oleh **Didik Purwanto**")

# --- HEADER UTAMA ---
st.markdown(
    '<p class="main-header">⚡ Portal Aplikasi & Tools Didik Purwanto</p>',
    unsafe_allow_html=True,
)
st.markdown(
    '<p class="sub-header">Pusat akses cepat untuk seluruh aplikasi web, kalkulator teknik, dan sistem analisis yang telah dikembangkan.</p>',
    unsafe_allow_html=True,
)

# --- DATA APLIKASI ---
apps = [
    {
        "title": "Aplikasi Sistem PLTS",
        "category": "⚡ Energi Terbarukan & PLTS",
        "url": "https://didikpurwanto180919-maker-plts--app-mdtosn.streamlit.app/",
        "desc": "Tool utama untuk perancangan, simulasi, dan kalkulasi sistem Pembangkit Listrik Tenaga Surya.",
        "icon": "☀️",
    },
    {
        "title": "Jaringan PLTS (GRT Surya)",
        "category": "⚡ Energi Terbarukan & PLTS",
        "url": "https://didikpurwanto180919-maker-jaringan-plts-grtsurya-app-jeufci.streamlit.app/",
        "desc": "Pemodelan, analisis jaringan, dan instalasi sistem kelistrikan PLTS.",
        "icon": "🔌",
    },
    {
        "title": "Sea Water Intake",
        "category": "🌊 Kelautan & Infrastruktur Air",
        "url": "https://didikpurwanto180919-maker-sea-water-intake-app-tcwiy5.streamlit.app/",
        "desc": "Perhitungan, pemantauan, dan analisis operasional sistem pengambilan air laut.",
        "icon": "🌊",
    },
    {
        "title": "Pasang Surut Air Laut",
        "category": "🌊 Kelautan & Infrastruktur Air",
        "url": "https://didikpurwanto180919-maker-pasang-surut-sea-water-app-btvtmh.streamlit.app/",
        "desc": "Prediksi dan pemantauan data pasang surut (tide) untuk kebutuhan infrastruktur pesisir.",
        "icon": "📈",
    },
    {
        "title": "Saham Real-Time",
        "category": "📈 Keuangan & Analisis Saham",
        "url": "https://didikpurwanto180919-maker-saham-realtime-app-niozha.streamlit.app/",
        "desc": "Pemantauan pergerakan harga instrumen saham secara langsung (real-time).",
        "icon": "📊",
    },
    {
        "title": "Prediksi Saham (LSTM)",
        "category": "📈 Keuangan & Analisis Saham",
        "url": "https://didikpurwanto180919-maker-sah-stockprice-prediction-lstm-efcdzl.streamlit.app/",
        "desc": "Pemodelan machine learning berbasis LSTM untuk prediksi tren harga saham.",
        "icon": "🤖",
    },
    {
        "title": "Portal Aplikasi Utama",
        "category": "🔗 Utilitas & Referensi",
        "url": "https://didikpurwanto180919-maker-didik-pur-app-1iqrn0.streamlit.app/",
        "desc": "Aplikasi personal/maker utama yang merangkum berbagai utilitas pendukung.",
        "icon": "🚀",
    },
    {
        "title": "Claude Artifact Viewer",
        "category": "🔗 Utilitas & Referensi",
        "url": "https://claude.ai/artifact/QLsJRaeZrdZreMywkgeH3F",
        "desc": "Referensi artefak kode, desain, atau catatan riset eksternal.",
        "icon": "📑",
    },
]

# Filter berdasarkan pilihan sidebar
if kategori_pilihan != "Semua Kategori":
    filtered_apps = [app for app in apps if app["category"] == kategori_pilihan]
else:
    filtered_apps = apps

# --- TAMPILKAN DALAM GRID (2 KOLOM) ---
col1, col2 = st.columns(2)

for index, app in enumerate(filtered_apps):
    # Bergantian kolom kiri dan kanan
    target_col = col1 if index % 2 == 0 else col2

    with target_col:
        st.markdown(
            f"""
        <div class="card">
            <h3>{app['icon']} {app['title']}</h3>
            <p><b>Kategori:</b> {app['category']}</p>
            <p>{app['desc']}</p>
        </div>
        """,
            unsafe_allow_html=True,
        )

        # Tombol aksi interaktif Streamlit
        st.link_button(
            f"🔗 Buka {app['title']}", app["url"], use_container_width=True
        )
        st.write("")  # Spasi antar kartu

# --- BAGIAN TAMBAHAN: EMBED PREVIEW (OPSIONAL) ---
st.markdown("---")
st.subheader("🖥️ Quick Preview Aplikasi")
st.markdown(
    "Pilih salah satu aplikasi di bawah untuk melihat atau menggunakannya langsung di dalam halaman ini:"
)

app_names = [app["title"] for app in apps]
selected_preview = st.selectbox("Pilih Aplikasi untuk Preview:", app_names)

# Cari URL yang sesuai dengan pilihan preview
selected_url = next(
    app["url"] for app in apps if app["title"] == selected_preview
)

# Tampilkan menggunakan komponen iframe Streamlit
st.components.v1.iframe(selected_url, height=600, scrolling=True)